name: my_dart_api
description: A REST API with Dart
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_cors: ^1.1.0
  
  # Для работы с JSON (опционально)
  json_annotation: ^4.8.0
  
  # Для баз данных (выберите нужную)
  postgres: ^2.5.0
  # или mongo_dart: ^0.7.5
  # или sqlite3: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.0
  json_serializable: ^6.5.0
  test: ^1.21.0